'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        return queryInterface.bulkInsert('Users', [
            {
                first_name: 'user',
                last_name: '1',
                birthday: '2022-01-01',
                gender: 'male',
                user_name: 'user login 1',
                password: 'Abc@1234',
                group_id: 1,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '2',
                birthday: '2022-02-01',
                gender: 'male',
                user_name: 'user login 2',
                password: 'Abc@1234',
                group_id: 1,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '3',
                birthday: '2022-03-01',
                gender: 'male',
                user_name: 'user login 3',
                password: 'Abc@1234',
                group_id: 1,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '4',
                birthday: '2022-04-01',
                gender: 'male',
                user_name: 'user login 4',
                password: 'Abc@1234',
                group_id: 1,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '5',
                birthday: '2022-05-01',
                gender: 'male',
                user_name: 'user login 5',
                password: 'Abc@1234',
                group_id: 1,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '6',
                birthday: '2022-06-01',
                gender: 'male',
                user_name: 'user login 6',
                password: 'Abc@1234',
                group_id: 1,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '7',
                birthday: '2022-07-01',
                gender: 'male',
                user_name: 'user login 7',
                password: 'Abc@1234',
                group_id: 1,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '8',
                birthday: '2022-08-01',
                gender: 'male',
                user_name: 'user login 8',
                password: 'Abc@1234',
                group_id: 1,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '9',
                birthday: '2022-09-01',
                gender: 'male',
                user_name: 'user login 9',
                password: 'Abc@1234',
                group_id: 1,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '10',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 10',
                password: 'Abc@1234',
                group_id: 1,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '11',
                birthday: '2022-01-01',
                gender: 'male',
                user_name: 'user login 11',
                password: 'Abc@1234',
                group_id: 2,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '12',
                birthday: '2022-02-01',
                gender: 'male',
                user_name: 'user login 12',
                password: 'Abc@1234',
                group_id: 2,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '13',
                birthday: '2022-03-01',
                gender: 'male',
                user_name: 'user login 13',
                password: 'Abc@1234',
                group_id: 2,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '14',
                birthday: '2022-04-01',
                gender: 'male',
                user_name: 'user login 14',
                password: 'Abc@1234',
                group_id: 2,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '15',
                birthday: '2022-05-01',
                gender: 'male',
                user_name: 'user login 15',
                password: 'Abc@1234',
                group_id: 2,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '16',
                birthday: '2022-06-01',
                gender: 'male',
                user_name: 'user login 16',
                password: 'Abc@1234',
                group_id: 2,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '17',
                birthday: '2022-07-01',
                gender: 'male',
                user_name: 'user login 17',
                password: 'Abc@1234',
                group_id: 2,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '18',
                birthday: '2022-08-01',
                gender: 'male',
                user_name: 'user login 18',
                password: 'Abc@1234',
                group_id: 2,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '19',
                birthday: '2022-09-01',
                gender: 'male',
                user_name: 'user login 19',
                password: 'Abc@1234',
                group_id: 2,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '20',
                birthday: '2022-0-01',
                gender: 'male',
                user_name: 'user login 20',
                password: 'Abc@1234',
                group_id: 2,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '21',
                birthday: '2022-01-01',
                gender: 'male',
                user_name: 'user login 21',
                password: 'Abc@1234',
                group_id: 3,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '22',
                birthday: '2022-02-01',
                gender: 'male',
                user_name: 'user login 22',
                password: 'Abc@1234',
                group_id: 3,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '23',
                birthday: '2022-03-01',
                gender: 'male',
                user_name: 'user login 23',
                password: 'Abc@1234',
                group_id: 3,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '24',
                birthday: '2022-04-01',
                gender: 'male',
                user_name: 'user login 24',
                password: 'Abc@1234',
                group_id: 3,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '25',
                birthday: '2022-05-01',
                gender: 'male',
                user_name: 'user login 25',
                password: 'Abc@1234',
                group_id: 3,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '26',
                birthday: '2022-06-01',
                gender: 'male',
                user_name: 'user login 26',
                password: 'Abc@1234',
                group_id: 3,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '27',
                birthday: '2022-07-01',
                gender: 'male',
                user_name: 'user login 27',
                password: 'Abc@1234',
                group_id: 3,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '28',
                birthday: '2022-08-01',
                gender: 'male',
                user_name: 'user login 28',
                password: 'Abc@1234',
                group_id: 3,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '29',
                birthday: '2022-09-01',
                gender: 'male',
                user_name: 'user login 29',
                password: 'Abc@1234',
                group_id: 3,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '30',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 30',
                password: 'Abc@1234',
                group_id: 3,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '31',
                birthday: '2022-01-01',
                gender: 'male',
                user_name: 'user login 31',
                password: 'Abc@1234',
                group_id: 4,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '32',
                birthday: '2022-02-01',
                gender: 'male',
                user_name: 'user login 32',
                password: 'Abc@1234',
                group_id: 4,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '33',
                birthday: '2022-03-01',
                gender: 'male',
                user_name: 'user login 33',
                password: 'Abc@1234',
                group_id: 4,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '34',
                birthday: '2022-04-01',
                gender: 'male',
                user_name: 'user login 34',
                password: 'Abc@1234',
                group_id: 4,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '35',
                birthday: '2022-05-01',
                gender: 'male',
                user_name: 'user login 35',
                password: 'Abc@1234',
                group_id: 4,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '36',
                birthday: '2022-06-01',
                gender: 'male',
                user_name: 'user login 36',
                password: 'Abc@1234',
                group_id: 4,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '37',
                birthday: '2022-07-01',
                gender: 'male',
                user_name: 'user login 37',
                password: 'Abc@1234',
                group_id: 4,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '38',
                birthday: '2022-08-01',
                gender: 'male',
                user_name: 'user login 38',
                password: 'Abc@1234',
                group_id: 4,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '39',
                birthday: '2022-09-01',
                gender: 'male',
                user_name: 'user login 39',
                password: 'Abc@1234',
                group_id: 4,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '40',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 40',
                password: 'Abc@1234',
                group_id: 4,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '41',
                birthday: '2022-01-01',
                gender: 'male',
                user_name: 'user login 41',
                password: 'Abc@1234',
                group_id: 5,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '42',
                birthday: '2022-02-01',
                gender: 'male',
                user_name: 'user login 42',
                password: 'Abc@1234',
                group_id: 5,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '43',
                birthday: '2022-03-01',
                gender: 'male',
                user_name: 'user login 43',
                password: 'Abc@1234',
                group_id: 5,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '44',
                birthday: '2022-04-01',
                gender: 'male',
                user_name: 'user login 44',
                password: 'Abc@1234',
                group_id: 5,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '45',
                birthday: '2022-05-01',
                gender: 'male',
                user_name: 'user login 45',
                password: 'Abc@1234',
                group_id: 5,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '46',
                birthday: '2022-06-01',
                gender: 'male',
                user_name: 'user login 46',
                password: 'Abc@1234',
                group_id: 5,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '47',
                birthday: '2022-07-01',
                gender: 'male',
                user_name: 'user login 47',
                password: 'Abc@1234',
                group_id: 5,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '48',
                birthday: '2022-08-01',
                gender: 'male',
                user_name: 'user login 48',
                password: 'Abc@1234',
                group_id: 5,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '49',
                birthday: '2022-09-01',
                gender: 'male',
                user_name: 'user login 49',
                password: 'Abc@1234',
                group_id: 5,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '50',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 50',
                password: 'Abc@1234',
                group_id: 5,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '51',
                birthday: '2022-01-01',
                gender: 'male',
                user_name: 'user login 51',
                password: 'Abc@1234',
                group_id: 6,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '52',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 52',
                password: 'Abc@1234',
                group_id: 6,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '53',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 53',
                password: 'Abc@1234',
                group_id: 6,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '54',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 54',
                password: 'Abc@1234',
                group_id: 6,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '55',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 55',
                password: 'Abc@1234',
                group_id: 6,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '56',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 56',
                password: 'Abc@1234',
                group_id: 6,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '57',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 57',
                password: 'Abc@1234',
                group_id: 6,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '58',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 58',
                password: 'Abc@1234',
                group_id: 6,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '59',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 59',
                password: 'Abc@1234',
                group_id: 6,
                createdAt: new Date(),
                updatedAt: new Date()
            },
            {
                first_name: 'user',
                last_name: '60',
                birthday: '2022-10-01',
                gender: 'male',
                user_name: 'user login 60',
                password: 'Abc@1234',
                group_id: 6,
                createdAt: new Date(),
                updatedAt: new Date()
            },

        ]);
    },

    async down(queryInterface, Sequelize) {
        return queryInterface.bulkDelete('Users', null, {});
    }
};
